# Generated by Django 3.0.5 on 2020-05-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthCredentials',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('scope', models.TextField()),
                ('token_type', models.CharField(max_length=128)),
                ('expires_at', models.FloatField()),
            ],
            options={
                'db_table': 'OAuthCredentials',
            },
        ),
        migrations.CreateModel(
            name='OAuthUser',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('login_id', models.BigIntegerField()),
                ('provider', models.CharField(max_length=64)),
                ('token', models.TextField()),
                ('login', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('thumbnail', models.TextField()),
            ],
            options={
                'db_table': 'OAuthUser',
            },
        ),
    ]
